FortLeaner: mod_const Module Reference
mod_const Module Reference
A module that defines useful constants.
Variables
real(kind=8), parameter pi_ = 3.14159265358979323846264338327950288d0
real(kind=8), parameter epsilon_ = 10d-8
real(kind=8), parameter max_real64 = huge(0d0)
real(kind=8), parameter min_real64 = -huge(0d0)
integer(kind=8), parameter max_int64 = huge(0_8)
integer(kind=8), parameter min_int64 = -huge(0_8)
real(kind=4), parameter max_real32 = huge(0.0)
real(kind=4), parameter min_real32 = -huge(0.0)
integer(kind=4), parameter max_int32 = huge(0)
integer(kind=4), parameter min_int32 = -huge(0)
logical(kind=4), parameter t_ = .true.
logical(kind=4), parameter f_ = .false.
integer(kind=8), parameter buffer_get_minmax =31
integer(kind=8), parameter max_test_iteration =100000000
integer(kind=8), parameter cache_size_multi_mat_vec =7
integer(kind=8), parameter max_rec_depth = 0
Detailed Description
A module that defines useful constants.
Variable Documentation
buffer_get_minmax
integer(kind=8), parameter mod_const::buffer_get_minmax =31
Definition at line 21 of file mod_const.f90.
     integer(kind=8), parameter :: buffer_get_minmax=31
cache_size_multi_mat_vec
integer(kind=8), parameter mod_const::cache_size_multi_mat_vec =7
Definition at line 24 of file mod_const.f90.
Referenced by mod_linalg::multi_mat_vec_with_indices_r8().
     integer(kind=8), parameter :: cache_size_multi_mat_vec=7
epsilon_
real(kind=8), parameter mod_const::epsilon_ = 10d-8
Definition at line 6 of file mod_const.f90.
     real(kind=8), parameter :: epsilon_ = 10d-8
f_
logical(kind=4), parameter mod_const::f_ = .false.
Definition at line 19 of file mod_const.f90.
Referenced by mod_linear_regression::fit_multiple_lasso_regression(), mod_linear_regression::fit_multiple_linear_regression(), mod_linear_regression::fit_multiple_ridge_regression(), mod_linear_regression::new_lasso_regression(), mod_linear_regression::new_linear_regression(), and mod_linear_regression::new_ridge_regression().
     logical(kind=4), parameter :: f_ = .false.
max_int32
integer(kind=4), parameter mod_const::max_int32 = huge(0)
Definition at line 15 of file mod_const.f90.
     integer(kind=4), parameter :: max_int32  =  huge(0)
max_int64
integer(kind=8), parameter mod_const::max_int64 = huge(0_8)
Definition at line 10 of file mod_const.f90.
     integer(kind=8), parameter :: max_int64  =  huge(0_8)
max_real32
real(kind=4), parameter mod_const::max_real32 = huge(0.0)
Definition at line 13 of file mod_const.f90.
     real(kind=4), parameter    :: max_real32 =  huge(0.0)
max_real64
real(kind=8), parameter mod_const::max_real64 = huge(0d0)
Definition at line 8 of file mod_const.f90.
     real(kind=8), parameter    :: max_real64 =  huge(0d0)
max_rec_depth
integer(kind=8), parameter mod_const::max_rec_depth = 0
Definition at line 26 of file mod_const.f90.
     integer(kind=8), parameter :: max_rec_depth = 0
max_test_iteration
integer(kind=8), parameter mod_const::max_test_iteration =100000000
Definition at line 22 of file mod_const.f90.
     integer(kind=8), parameter :: max_test_iteration=100000000
min_int32
integer(kind=4), parameter mod_const::min_int32 = -huge(0)
Definition at line 16 of file mod_const.f90.
     integer(kind=4), parameter :: min_int32  = -huge(0)
min_int64
integer(kind=8), parameter mod_const::min_int64 = -huge(0_8)
Definition at line 11 of file mod_const.f90.
     integer(kind=8), parameter :: min_int64  = -huge(0_8)
min_real32
real(kind=4), parameter mod_const::min_real32 = -huge(0.0)
Definition at line 14 of file mod_const.f90.
     real(kind=4), parameter    :: min_real32 = -huge(0.0)
min_real64
real(kind=8), parameter mod_const::min_real64 = -huge(0d0)
Definition at line 9 of file mod_const.f90.
     real(kind=8), parameter    :: min_real64 = -huge(0d0)
pi_
real(kind=8), parameter mod_const::pi_ = 3.14159265358979323846264338327950288d0
Definition at line 5 of file mod_const.f90.
     real(kind=8), parameter :: pi_ = 3.14159265358979323846264338327950288d0
t_
logical(kind=4), parameter mod_const::t_ = .true.
Definition at line 18 of file mod_const.f90.
Referenced by mod_linear_regression::fit_multiple_lasso_regression(), mod_linear_regression::fit_multiple_linear_regression(), mod_linear_regression::fit_multiple_ridge_regression(), mod_linear_regression::fit_simple_lasso_regression(), mod_linear_regression::fit_simple_linear_regression(), and mod_linear_regression::fit_simple_ridge_regression().
     logical(kind=4), parameter :: t_ = .true.