name: Publish to TestPyPI

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheels with cibuildwheel (Linux x86_64)
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BUILD: cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BEFORE_ALL_LINUX: |
            sed -i -e 's|^mirrorlist=|#mirrorlist=|g' \
                   -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' \
                   /etc/yum.repos.d/CentOS-*.repo
            yum install -y openblas-devel gcc-gfortran
        with:
          package-dir: .
          output-dir: ./dist

      - name: Build sdist
        run: |
          python -m pip install --upgrade build
          python -m build --sdist . -o dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
